#!/bin/bash
set -x -e -o pipefail

### [version] [branch] revision[-dirty] build_date_time
gitver() {
	local ver branch rev dirty
	ver="$(git tag -l --sort=-version:refname --merged HEAD 'v*' | head -n 1)"
	branch="$(git rev-parse --abbrev-ref HEAD)"
	rev="$(git log -1 --format='%h')"
	git update-index -q --refresh --unmerged >/dev/null
	git diff-index --quiet HEAD || dirty="-dirty"
	test "$branch" = "HEAD" || test "$branch" = "master" && branch=

	echo "${ver:+$ver }${branch:+$branch }$rev$dirty $(date -u +"%F_%T")"
}

rm -rf bin/
mkdir bin/
CGO_ENABLED=0 go get -v -installsuffix static ./...
CGO_ENABLED=0 GOBIN=$PWD/bin go install -v -installsuffix static \
	-ldflags "-X 'main.ver=$(gitver)'" ./...

docker build -t ${PWD##*/} .
